indent-width = 4
line-length = 100

[lint]
select = ["ALL"]
ignore = [
  "EM101", # raw-string-in-exception
  "S101", # assert
  "TRY003", # raise-vanilla-args
]
fixable = ["ALL"]
unfixable = []
future-annotations = true

[lint.per-file-ignores]
"**/{tests}/*" = [
  "PLR2004", # magic-value-comparison
  "D107", # undocumented-public-init
  "SLF001", # private-member-access
  "PLR0913", # too-many-arguments
  "PLR0917", # too-many-positional-arguments
]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint.pydocstyle]
convention = "google"

[lint.isort]
section-order = ["future", "local-folder", "first-party", "third-party", "standard-library"]
known-local-folder = ["packy", "constants", "core", "models", "task", "ui", "utils", "views", "widgets"]
known-first-party = ["packy", "constants", "core", "models", "task", "ui", "utils", "views", "widgets"]

[lint.isort.import-heading]
future = "Future library"
local-folder = "Local application"
first-party = "Local application"
third-party = "Third-party"
standard-library = "Standard library"